# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: node:latest

# Pick zero or more services to be used on all builds.
# Only needed when using a docker container to run your tests in.
# Check out: http://docs.gitlab.com/ce/ci/docker/using_docker_images.html#what-is-a-service

stages:
  - build
  - test
  - pre-deploy
  - deploy

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
setup_env:
  stage: build
  script:
    - npm install

cache:
  paths:
  - node_modules/

test_unit:
  stage: test
  script:
   - npm run test-unit

test_integration:
  stage: test
  variables:
    NODE_ENV: testing
    MONGO_INITDB_ROOT_USERNAME: teste
    MONGO_INITDB_ROOT_PASSWORD: secret
    MONGO_INITDB_DATABASE: easy-invoice
  services: 
    - mongo:latest
  script:
    - npm run test-integration

update_sandbox:
  stage: deploy
  image: python:latest
  only:
    - /^dev$/
  variables:
    DEPLOY_INSTANCE_ID: mi-053815d2db60caec8
    COMMAND_COMMENT: update-sandbox-env
  script:
    - bash ./scripts/deploy.sh
  when: on_success